myshop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

myshop/coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from payment import webhooks


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

urlpatterns += [
    path(
        'payment/webhook/',
        webhooks.stripe_webhook,
        name='stripe-webhook'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

myshop/orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _


app_name = 'orders'


urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path(
        'admin/order/<int:order_id>/',
        views.admin_order_detail,
        name='admin_order_detail'
    ),
    path(
        'admin/order/<int:order_id>/pdf/',
        views.admin_order_pdf,
        name='admin_order_pdf'
    ),
]

myshop/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

# A list of tuples representing the available product quantity choices.
# Each tuple contains an integer value and its corresponding string label.
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """
    A form class to validate the addition of a product to the cart.

    Attributes:
        quantity (forms.TypedChoiceField): A field to select the desired quantity.
        override (forms.BooleanField): A hidden field to indicate whether to override existing cart items.
    """

    # A field to select the desired quantity from the available choices.
    quantity = forms.TypedChoiceField(
        # The list of available quantity choices.
        choices=PRODUCT_QUANTITY_CHOICES,
        # Coerce the selected value to an integer for validation purposes.
        coerce=int,
        # The label to display next to the field in the form.
        label=_('Quantity')
    )

    # A hidden boolean field to indicate whether to override existing cart items.
    # This field is required=False by default, meaning it will not be displayed in the form.
    # However, when submitting the form with this field present, its value will override any existing cart items.
    override = forms.BooleanField(
        # Make the field optional (i.e., not required).
        required=False,
        # Initialize the field's value to False by default.
        initial=False,
        # Use a hidden input widget for this field so it won't be displayed in the form.
        widget=forms.HiddenInput
    )

myshop/cart/views.py
from coupons.forms import CouponApplyForm
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from shop.models import Product
from shop.recommender import Recommender

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    """
    Adds a product to the user's cart.

    Args:
        request (HttpRequest): The current HTTP request.
        product_id (int): The ID of the product to add.

    Returns:
        HttpResponse: A redirect to the cart detail page.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override'],
        )
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    """
    Removes a product from the user's cart.

    Args:
        request (HttpRequest): The current HTTP request.
        product_id (int): The ID of the product to remove.

    Returns:
        HttpResponse: A redirect to the cart detail page.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    """
    Displays the user's cart.

    Args:
        request (HttpRequest): The current HTTP request.

    Returns:
        HttpResponse: The cart detail page.
    """
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True}
        )
    coupon_apply_form = CouponApplyForm()

    r = Recommender()
    cart_products = [item['product'] for item in cart]
    if cart_products:
        recommended_products = r.suggest_products_for(
            cart_products, max_results=4
        )
    else:
        recommended_products = []

    return render(
        request,
        'cart/detail.html',
        {
            'cart': cart,
            'coupon_apply_form': coupon_apply_form,
            'recommended_products': recommended_products,
        },
    )

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load i18n static %}

{% block title %}
  {% translate "Your shopping cart" %}
{% endblock %}

{% block content %}
  <h1>{% translate "Your shopping cart" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>{% translate "Image" %}</th>
        <th>{% translate "Product" %}</th>
        <th>{% translate "Quantity" %}</th>
        <th>{% translate "Remove" %}</th>
        <th>{% translate "Unit price" %}</th>
        <th>{% translate "Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="{% translate "Update" %}">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="{% translate "Remove" %}">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>{% translate "Subtotal" %}</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
          <td>
            {% blocktranslate with code=cart.coupon.code discount=cart.coupon.discount %}
              "{{ code }}" coupon ({{ discount }}% off)
            {% endblocktranslate %}
          </td>
          <td colspan="4"></td>
          <td class="num neg">
            - ${{ cart.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>{% translate "Total" %}</td>
        <td colspan="4"></td>
        <td class="num">
          ${{ cart.get_total_price_after_discount|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>

  {% if recommended_products %}
  <div class="recommendations cart">
    <h3>{% translate "People who bought this also bought" %}</h3>
    {% for p in recommended_products %}
      <div class="item">
        <a href="{{ p.get_absolute_url }}">
          <img src="{% if p.image %}{{ p.image.url }}{% else %}
          {% static "img/no_image.png" %}{% endif %}">
        </a>
        <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
      </div>
    {% endfor %}
  </div>
{% endif %}

  <p>{% translate "Apply a coupon" %}:</p>
  <form action="{% url "coupons:apply" %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="{% translate "Apply" %}">
    {% csrf_token %}
  </form>
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button light">{% translate "Continue shopping" %}</a>
    <a href="{% url "orders:order_create" %}" class="button">{% translate "Checkout" %}</a>
  </p>
{% endblock %}