myshop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from payment import webhooks


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

urlpatterns += [
    path(
        'payment/webhook/',
        webhooks.stripe_webhook,
        name='stripe-webhook'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

myshop/payment/urls.py
from django.urls import path
from . import views, webhooks
from django.utils.translation import gettext_lazy as _


app_name = 'payment'


urlpatterns = [
    path(_('process/'), views.payment_process, name='process'),
    path(_('completed/'), views.payment_completed, name='completed'),
    path(_('canceled/'), views.payment_canceled, name='canceled'),
]

myshop/payment/models.py
from django.db import models

# Create your models here.

myshop/payment/views.py
from django.shortcuts import render, get_object_or_404, redirect
from decimal import Decimal
import stripe
from django.conf import settings
from django.urls import reverse
from orders.models import Order


# Создаем экземпляр Stripe
# Публичный ключ для подключения к API Stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION  # Версия API Stripe


def payment_process(request):
    """
    Обрабатывает процесс оплаты заказа.

    Если метод запроса POST и форма валидна, создаёт сессию оплаты Stripe,
    добавляет элементы заказа в сессию, создаёт купон для скидки (если есть),
    перенаправляет на форму оплаты Stripe.
    В противном случае отображает шаблон 'payment/process.html'.

    Args:
        request (HttpRequest): Текущий HTTP-запрос.

    Returns:
        HttpResponse: Возвращает ответ с либо отображением шаблона,
            либо перенаправлением на форму оплаты Stripe.
    """
    order_id = request.session.get('order_id')  # Получает ID заказа из сессии
    # Ищет заказ по ID и обрабатывает ошибку
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        # URL-адрес для перенаправления после успешной оплаты
        success_url = reverse('payment:completed')
        # URL-адрес для перенаправления при отмене оплаты
        cancel_url = reverse('payment:canceled')

        # Данные сессии оформления заказа Stripe
        session_data = {
            'mode': 'payment',  # Режим оплаты
            'client_reference_id': order.id,  # ID клиента в сессии
            'success_url': success_url,  # URL-адрес для перенаправления после успешной оплаты
            'cancel_url': cancel_url,  # URL-адрес для перенаправления при отмене оплаты
            'line_items': []  # Список элементов заказа
        }
        # Добавление элементов заказа в сессию оформления заказа Stripe
        for item in order.items.all():
            session_data['line_items'].append(
                {
                    'price_data': {  # Данные о цене
                        # Цена без десятичной точки
                        'unit_amount': int(item.price * Decimal('100')),
                        'currency': 'usd',  # Валюта
                        'product_data': {  # Данные о товаре
                            'name': item.product.name,  # Название товара
                        },
                    },
                    'quantity': item.quantity,  # Количество товаров
                }
            )
        # Создание купона для скидки (если есть)
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.coupon.code,
                percent_off=order.discount,
                duration='once'
            )
            session_data['discounts'] = [{'coupon': stripe_coupon.id}]
        # Создание сессии оплаты Stripe
        session = stripe.checkout.Session.create(**session_data)
        # Перенаправляет на форму оплаты Stripe
        return redirect(session.url, code=303)
    else:
        # Отображает шаблон 'payment/process.html' при GET-запросе
        return render(request, 'payment/process.html', locals())


def payment_completed(request):
    """
    Обрабатывает окончание процесса оплаты.

    Args:
        request (HttpRequest): Текущий HTTP-запрос.

    Returns:
        HttpResponse: Возвращает ответ с отображением шаблона.
    """
    return render(request, 'payment/completed.html')


def payment_canceled(request):
    """
    Обрабатывает отмену процесса оплаты.

    Args:
        request (HttpRequest): Текущий HTTP-запрос.

    Returns:
        HttpResponse: Возвращает ответ с отображением шаблона.
    """
    return render(request, 'payment/canceled.html')

myshop/payment/templates/payment/canceled.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block title %}{% translate "Payment canceled" %}{% endblock %}

{% block content %}
  <h1>{% translate "Your payment has not been processed" %}</h1>
  <p>{% translate "There was a problem processing your payment." %}</p>
{% endblock %}

myshop/payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block title %}{% translate "Payment successful" %}{% endblock %}

{% block content %}
  <h1>{% translate "Your payment was successful" %}</h1>
  <p>{% translate "Your payment has been processed successfully." %}</p>
{% endblock %}

myshop/payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load i18n static %}

{% block title %}{% translate "Pay your order" %}{% endblock %}

{% block content %}
  <h1>{% translate "Order summary" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>{% translate "Image" %}</th>
        <th>{% translate "Product" %}</th>
        <th>{% translate "Price" %}</th>
        <th>{% translate "Quantity" %}</th>
        <th>{% translate "Total" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.items.all %}
        <tr class="row{% cycle "1" "2" %}">
          <td>
            <img src="{% if item.product.image %}{{ item.product.image.url }}
            {% else %}{% static "img/no_image.png" %}{% endif %}">
          </td>
          <td>{{ item.product.name }}</td>
          <td class="num">${{ item.price }}</td>
          <td class="num">{{ item.quantity }}</td>
          <td class="num">${{ item.get_cost }}</td>
        </tr>
      {% endfor %}
      {% if order.coupon %}
        <tr class="subtotal">
          <td>{% translate "Subtotal" %}</td>
          <td colspan="3"></td>
          <td class="num">
            ${{ order.get_total_cost_before_discount|floatformat:2 }}
          </td>
        </tr>
        <tr>
          <td>
            {% blocktranslate with code=order.coupon.code discount=order.discount %}
              "{{ code }}" ({{ discount }}% off)
            {% endblocktranslate %}
          </td>
          <td colspan="3"></td>
          <td class="num neg">
            - ${{ order.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>{% translate "Total" %}</td>
        <td colspan="3"></td>
        <td class="num">
          ${{ order.get_total_cost|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>
  <form action="{% url "payment:process" %}" method="post">
    <input type="submit" value="{% translate "Pay now" %}">
    {% csrf_token %}
  </form>
{% endblock %}